#!/bin/bash

##This sript extracts the CDS from the output generated by the NCBI Datasets tool; and output the best aligned ##CDS to the CDS privided in *.fa files in the same folder

#Make a BED file for extraction from the rna.fna file
#The data_table.tsv file has to be manually corrected for missing entries and saved as data_table.csv

cut -d $'\t' -f 4,14 data_table.tsv|awk '{if(NR!=1){gsub(" ","_",$0);gsub(":"," ",$2);gsub("-"," ",$2); print $2" "$1}}'|awk '{print $1"\t"$2-1"\t"$3"\t"$4"::"$1":"$2-1"-"$3}'|awk '{if($1 != "" && $2 != "" && $3 != "" && $4 != ""){print $0}}' > extraction.bed

#Removes superfluous entries from header of FASTA file 

awk '{print $1}' rna.fna > temp_rna.fna

#Extract FASTA sequence from the data and split species-wise into <genus_species>.fasta

bedtools getfasta -fi temp_rna.fna -bed extraction.bed -name | awk '/^>/{split($1,a,"[.:]");gsub(">","",a[1])}{gsub(":","_",$0);print >> a[1]".fasta"}' 

mkdir individual_iso
mkdir isoforms_with_accession
mv *.fasta individual_iso

#Now, for each *.fa file provided, the alignment score (with *.fasta files) will be calculated and the best FASTA chosen and added to the appropriate folder. 

for j in *ref.fa

do

for i in individual_iso/*.fasta

do

water -asequence $j -bsequence $i -gapopen 10 -gapextend 0.5 -outfile align.out -aaccshow3 Y -adesshow3 Y -aformat score

bestrn=$(awk 'BEGIN{score=0;best=""}{gsub("\\(","",$0);gsub("\\)","",$0);if(score<$4){score=$4;best=$2}}END{print best}' align.out)

#echo $bestr

awk 'BEGIN{t=0}/'$bestrn'/{print $0; t=1; next}/^>/{t=0}{if(t==1){print $0}}' $i >> "${j%.fa}"_ortho.fa

done

done

for x in *ortho.fa
do

cp "$x" isoforms_with_accession

awk '{if($1~">") {gsub("__.*","", $1)}; print $0}'  $x > "${x%.fa}"@.fa

done

rm align.out
rm temp_rna.fna
rm *ortho.fa
